In [1]:
import numpy as np
import time 
import sys

# 1D

In [2]:
oneD=np.array([1,2,3])
print(oneD.shape)
print(oneD)


(3,)
[1 2 3]


In [3]:

print(oneD.T.shape)
print(oneD.T)


(3,)
[1 2 3]


# ND

In [4]:
x=np.array([[1,2,3,4]])
print(x)
print(x.shape)
print()
print(x.T)
print(x.T.shape)
# similar to list
print()
print(x[0])
print()
print(x.T[0])

[[1 2 3 4]]
(1, 4)

[[1]
 [2]
 [3]
 [4]]
(4, 1)

[1 2 3 4]

[1]


In [5]:
x.size

4

In [6]:
Zarr=np.zeros((2,2),int)
Zarr

array([[0, 0],
       [0, 0]])

In [7]:
Oarr=np.ones((3,4,))
Oarr

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [8]:
arr=np.arange(0,10,2)
arr

array([0, 2, 4, 6, 8])

linspace -- low ,high , parts (high and low also inlcuded) one range=(high-low)/part-1

In [9]:
arr1 = np.linspace(0, 1, 5)
arr1

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [10]:
#get number of dimensions
print(x.ndim)

2


In [11]:
#get number of elements
print(x.size)

4


In [12]:
print(x.dtype)

int64


In [13]:
print(x.shape)
print(x)

(1, 4)
[[1 2 3 4]]


In [14]:
y=x.reshape((2,2,1)) # does not modify original one
print(y.shape)
print(y)

(2, 2, 1)
[[[1]
  [2]]

 [[3]
  [4]]]


In [15]:
z=y.flatten()
print(z)

[1 2 3 4]


# Mathematical Operations

Addition/Subtraction -- Dimension should be exactly same

In [16]:
arr1=np.array([[1,2,3]])
arr2=np.array([[4,5,6]])
print(arr1+arr2)
print(arr2-arr1)
print(arr1*arr2)
print(arr2/arr1)
print(np.dot(arr1.T,arr2))
print(np.cross(arr1,arr2))


[[5 7 9]]
[[3 3 3]]
[[ 4 10 18]]
[[4.  2.5 2. ]]
[[ 4  5  6]
 [ 8 10 12]
 [12 15 18]]
[[-3  6 -3]]


# Statistical Methods

In [17]:
print(arr1.min())
print(arr2.min())

1
4


In [18]:
print(arr1.max())
print(arr2.max())

3
6


In [19]:
print(arr1.prod())
print(arr1.sum())
print(arr2.sum())
print(np.prod(arr2)) #4*5*6
print(np.dot(arr1,arr2.T))

6
6
15
120
[[32]]


In [20]:
print(arr1.mean())
print(np.mean(arr1))
print(np.sum(arr1))
print(np.max(arr1))

2.0
2.0
6
3


In [21]:
uq=np.array([1,2,2,4,5])
print(np.unique(uq))

[1 2 4 5]


In [22]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([[1], [2], [3]])
result = arr1 + arr2 # Broadcasting addition
print(result)

[[2 3 4]
 [3 4 5]
 [4 5 6]]


In [23]:
np.random.seed(20)
# Generating random numbers
rand_arr = np.random.rand(3, 3)
# Generating random integers
rand_ints = np.random.randint(0, 10, (3, 3))
print(rand_arr)
print(rand_ints)

[[0.5881308  0.89771373 0.89153073]
 [0.81583748 0.03588959 0.69175758]
 [0.37868094 0.51851095 0.65795147]]
[[3 0 6]
 [6 0 9]
 [5 7 5]]


 Inverse of a matrix , Determinant of Matrix

In [24]:

arr1=np.random.randint(0,10,(3,3))
print(arr1)
inv=np.linalg.inv(arr1)
print(inv)
print(np.linalg.det(inv))

[[2 6 9]
 [3 3 9]
 [0 6 2]]
[[-1.6         1.4         0.9       ]
 [-0.2         0.13333333  0.3       ]
 [ 0.6        -0.4        -0.4       ]]
0.03333333333333332
