In [3]:
import tensorflow as tf

In [5]:
print(tf.version)

<module 'tensorflow._api.v2.version' from 'C:\\Users\\satya\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python312\\site-packages\\tensorflow\\_api\\v2\\version\\__init__.py'>


# CREATING  TENSORS

In [ ]:
string =tf.Variable("my nmae is satya",tf.string)
number=tf.varibale(1234,tf.int16)
floating=tf.Variable(123.3254,tf.float64)

Rank/Degree of Tensor-- Number of dimensions of a tensor 
Above tensors have all 0 degree

In [7]:
rank1_tensor=tf.Variable(["satya","kushwaha"],tf.string)
rank2_tensor=tf.Variable([["hi"],["bro"]],tf.string)
print()
print(tf.rank(rank1_tensor))
print()
print(tf.rank(rank2_tensor))


tf.Tensor(1, shape=(), dtype=int32)

tf.Tensor(2, shape=(), dtype=int32)


In [8]:
print(rank1_tensor.shape)
print(rank2_tensor.shape)

(2,)
(2, 1)


CHANGING SHAPE OF TENSORS

In [14]:
tensor1=tf.ones([2,2,3])
print(tensor1)
tensor2=tf.reshape(tensor1,[2,3,2])
print(tensor2)
tensor3=tf.reshape(tensor1,[4,-1]) #when we only know number of rows
print(tensor3)

tf.Tensor(
[[[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]], shape=(2, 2, 3), dtype=float32)
tf.Tensor(
[[[1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]]], shape=(2, 3, 2), dtype=float32)
tf.Tensor(
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]], shape=(4, 3), dtype=float32)


Evaluating Tensors

In [16]:
# with tf.Session() as sess:
#     tensor1.eval()