#CREATING NUMPY ARRAYS

In [ ]:
import numpy as np

In [ ]:
#np array
a=np.array([1,2,3])
print(a)

[1 2 3]


In [ ]:
#2d / 3d
d2=np.array([[1,2],[2,3]])
print(b)
print()
d3=np.array([[[1],[2],[3]]])
print(d3)

[[1 2]
 [2 3]]

[[[1]
  [2]
  [3]]]


In [ ]:
#dtype
print(np.array([1,2,3],dtype=float))
print(np.array([1,0,3],dtype=bool))

[1. 2. 3.]
[ True False  True]


In [ ]:
#np.arange -- sprites 3rd arg
np.arange(1,11)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
#reshape
np.arange(1,11).reshape(5,2)

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10]])

In [ ]:
#np.ones and np.zeroes
print(np.ones((3,4)))
print()
print(np.zeros((2,6)))

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]

[[0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]]


In [ ]:
#np.random -- generate numbers between 0 and 1
np.random.random((3,4))

array([[0.7935378 , 0.10479336, 0.04668009, 0.93156197],
       [0.10425117, 0.18985188, 0.64044235, 0.42555989],
       [0.63739468, 0.0287978 , 0.18389581, 0.67582863]])

In [ ]:
#np.linspace(lower range,upper range,how amny numbers,dtype=int/float by default)---generate points in equal space
np.linspace(-10,10,10)

array([-10.        ,  -7.77777778,  -5.55555556,  -3.33333333,
        -1.11111111,   1.11111111,   3.33333333,   5.55555556,
         7.77777778,  10.        ])

In [ ]:
#np.identity --identity matrix (n*n)
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

#ATTRBUTES

In [ ]:
a1=np.arange(10)
a2=np.arange(12,dtype=float).reshape(3,4)
a3=np.arange(8).reshape(2,2,2)
print(a1)
print()
print(a2)
print()
print(a3)

[0 1 2 3 4 5 6 7 8 9]

[[ 0.  1.  2.  3.]
 [ 4.  5.  6.  7.]
 [ 8.  9. 10. 11.]]

[[[0 1]
  [2 3]]

 [[4 5]
  [6 7]]]


In [ ]:
#ndim
print(a1.ndim)
print(a2.ndim)
print(a3.ndim)

1
2
3


In [ ]:
#shape
print(a1.shape)
print(a2.shape)
print(a3.shape)

(10,)
(3, 4)
(2, 2, 2)


In [ ]:
#size---total number of elements
print(a1.size)
print(a2.size)
print(a3.size)

10
12
8


In [ ]:
#dtype
print(a1.dtype)

int64


#CHANGING DATATYPES

In [ ]:
#astype
a1.astype(np.int32)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=int32)

#ARRAY OPERATIONS

In [ ]:
#reshape

In [ ]:
#scalar operation(all will work)
a1*2

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [ ]:
#relational operators(<,<=,>,>=,==)
a2>5

array([[False, False, False, False],
       [False, False,  True,  True],
       [ True,  True,  True,  True]])

In [ ]:
#vector operations
x=np.array([[1,2],[3,4]])
y=np.array([[9,2],[4,1]])
print(x+y)
print()
print(x/)
print(x*y)

[[10  4]
 [ 7  5]]
[[ 9  4]
 [12  4]]


#ARRAY FUNCTIONS

In [55]:
a1=np.random.random((3,3))
a1=np.round(a1*100)
print(a1)

[[40. 80. 63.]
 [54. 77. 23.]
 [43. 51. 19.]]


In [57]:
#min/max/sum/prod
print(np.max(a1))
print(np.min(a1))
print(np.sum(a1))
print(np.prod(a1))

80.0
19.0
450.0
803332026604800.0


In [60]:
#getting row or column wise anything
print(np.max(a1,axis=1)) #row
print(np.max(a1,axis=0)) #col

[80. 77. 51.]
[54. 80. 63.]


In [62]:
#mean,median,mode -- also axis=0/1 can be done
np.mean(a1)

50.0

In [63]:
#trignometreic functions
np.sin(a1)

array([[ 0.74511316, -0.99388865,  0.1673557 ],
       [-0.55878905,  0.99952016, -0.8462204 ],
       [-0.83177474,  0.67022918,  0.14987721]])

In [68]:
#dot product
mat1=np.random.random((3,4))
print(mat1)
print()
mat2=np.random.random((4,1))
print(mat2)
print()
print(np.dot(mat1,mat2))
print()

[[0.29289072 0.42464201 0.36232509 0.16028432]
 [0.32943697 0.73167435 0.84172421 0.69262086]
 [0.11582855 0.00095743 0.23749285 0.3996562 ]]

[[0.82946005]
 [0.98375864]
 [0.20250279]
 [0.43481502]]

[[0.80375226]
 [1.46465922]
 [0.31888652]]



In [71]:
#log and exponents
print(np.log(a1))
print(np.exp(a1))

[[3.68887945 4.38202663 4.14313473]
 [3.98898405 4.34380542 3.13549422]
 [3.76120012 3.93182563 2.94443898]]
[[2.35385267e+17 5.54062238e+34 2.29378316e+27]
 [2.83075330e+23 2.75851345e+33 9.74480345e+09]
 [4.72783947e+18 1.40934908e+22 1.78482301e+08]]


In [78]:
#round/floor/ceil
x=np.random.random((2,2))*100
print(x)
print()
print(np.round(x))
print()
print(np.ceil(x))
print()
print(np.floor(x))
print()

[[31.33384164 87.50772657]
 [93.98013169  5.32139225]]

[[31. 88.]
 [94.  5.]]

[[32. 88.]
 [94.  6.]]

[[31. 87.]
 [93.  5.]]



#INDEXING AND SLICING

In [81]:
a1=np.arange(10)
a2=np.arange(12).reshape(3,4)
a3=np.arange(8).reshape(2,2,2)
print(a1)
print()
print(a2)
print()
print(a3)
print()

[0 1 2 3 4 5 6 7 8 9]

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]

[[[0 1]
  [2 3]]

 [[4 5]
  [6 7]]]



In [85]:
#finding element
print(a2[1][2])
print(a2[1,2])
print(a3[1,0,1]) #which 2d -> which row ->which col

6
6
5


In [87]:
a1[2:7] #1d

array([2, 3, 4, 5, 6])

In [89]:
print(a2[0,:]) #1st row ,all columns
print(a2[:,3]) #3rd column, all rows

[0 1 2 3]
[ 3  7 11]


In [90]:
#sexy as fuck--fetch 5,6,9,10
a2[1:,1:3]

array([[ 5,  6],
       [ 9, 10]])

#ITERATION OVER NUMPY ARRAYS

In [94]:
a1
for i in a1:
  print(i)

0
1
2
3
4
5
6
7
8
9


In [95]:
a2
for i in a2:
  print(i)

[0 1 2 3]
[4 5 6 7]
[ 8  9 10 11]


In [96]:
a3
for i in a3:
  print(i)

[[0 1]
 [2 3]]
[[4 5]
 [6 7]]


In [98]:
#flatterns in 1d and then itwerates #nditer(array)
for i in np.nditer(a3):
  print(i)

0
1
2
3
4
5
6
7


#RESHAPING TRANSPOSE RAVEL

In [100]:
print(a2)
print(a2.T)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]


In [101]:
#ravel -- converts nd array to 1d
a2.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

#STACKING--VSTACK,HSTACK

In [102]:
#horizontal stacking
a1=np.random.random((2,2))
a2=np.random.random((2,2))
print(a1)
print()
print(a2)
print()

[[0.63117993 0.10421114]
 [0.96831164 0.48410824]]
[[0.88166542 0.70509634]
 [0.57877537 0.72607919]]


In [104]:
print(np.hstack((a1,a2)))
print(np.vstack((a1,a2)))

[[0.63117993 0.10421114 0.88166542 0.70509634]
 [0.96831164 0.48410824 0.57877537 0.72607919]]
[[0.63117993 0.10421114]
 [0.96831164 0.48410824]
 [0.88166542 0.70509634]
 [0.57877537 0.72607919]]


#SPLITTING

In [105]:
#hsplit and vsplit