In [4]:
import numpy as np

1. numpy.random.seed(seed=None)
Purpose: Initialize the random number generator for reproducibility.
Example: np.random.seed(42)

In [6]:
np.random.seed(42)

2. numpy.random.rand(d0, d1, ..., dn)
Purpose: Generate an array of random floats uniformly distributed over [0, 1) with the given shape.
Example: np.random.rand(3, 2) generates a 3x2 array.

In [9]:
print(np.random.rand(3,2))

[[0.54671028 0.18485446]
 [0.96958463 0.77513282]
 [0.93949894 0.89482735]]


3. numpy.random.randn(d0, d1, ..., dn)
Purpose: Generate an array of random floats from the standard normal distribution (mean 0, variance 1).
Example: np.random.randn(3, 2) generates a 3x2 array.

In [11]:
print(np.random.randn(3,2))

[[ 0.17136828 -0.11564828]
 [-0.3011037  -1.47852199]
 [-0.71984421 -0.46063877]]


4. numpy.random.randint(low, high=None, size=None, dtype=int)
Purpose: Generate random integers between low (inclusive) and high (exclusive). If high is not provided, it generates integers between 0 and low.
Example: np.random.randint(0, 10, size=(3, 3)) generates a 3x3 array of random integers between 0 and 9.

In [12]:
print(np.random.randint(1,10,(3,2)))

[[9 1]
 [9 7]
 [9 8]]


5. numpy.random.choice(a, size=None, replace=True, p=None)
Purpose: Generate a random sample from a given 1-D array or integer.
Example: np.random.choice([1, 2, 3, 4, 5], size=3, replace=False) generates 3 unique random samples from the list.

In [17]:
print(np.random.choice([12,13,14],3,replace=False))

[13 12 14]


6. numpy.random.uniform(low=0.0, high=1.0, size=None)
Purpose: Generate random floats uniformly distributed between low and high.
Example: np.random.uniform(1.5, 5.5, size=(2, 3)) generates a 2x3 array.

In [18]:
print(np.random.uniform(0,2,(4,3)))

[[1.21191995 1.85260176 1.30215405]
 [1.82991935 1.70007716 0.89890135]
 [0.19082023 0.7416365  1.33768251]
 [1.33184471 1.18259558 0.54944359]]


7. numpy.random.normal(loc=0.0, scale=1.0, size=None)
Purpose: Generate random numbers from a normal (Gaussian) distribution with mean loc and standard deviation scale.
Example: np.random.normal(0, 1, size=(3, 3)) generates a 3x3 array.

8. numpy.random.random(size=None)
Purpose: Generate random floats uniformly distributed over [0, 1).
Example: np.random.random(size=(2, 3)) generates a 2x3 array.

In [19]:
np.random.random(size=(2, 3))

array([[0.56124343, 0.38292687, 0.9717121 ],
       [0.84891382, 0.72172952, 0.23598492]])

9. numpy.random.beta(a, b, size=None)
Purpose: Generate random numbers from a Beta distribution with parameters a and b.
Example: np.random.beta(0.5, 0.5, size=5) generates an array of 5 elements.
10. numpy.random.binomial(n, p, size=None)
Purpose: Generate random numbers from a binomial distribution with n trials and probability p.
Example: np.random.binomial(10, 0.5, size=10) generates an array of 10 elements.
11. numpy.random.poisson(lam=1.0, size=None)
Purpose: Generate random numbers from a Poisson distribution with rate parameter lam.
Example: np.random.poisson(5, size=10) generates an array of 10 elements.
12. numpy.random.gamma(shape, scale=1.0, size=None)
Purpose: Generate random numbers from a Gamma distribution.
Example: np.random.gamma(2.0, 2.0, size=5) generates an array of 5 elements

13. numpy.random.permutation(x)
Purpose: Randomly permute a sequence or return a permuted range.
Example: np.random.permutation(10) returns a shuffled array [0, 1, ..., 9].

In [22]:
x=np.random.permutation(10)
print(x)
print(type(x))

[8 0 4 1 9 5 7 2 6 3]
<class 'numpy.ndarray'>


14. numpy.random.shuffle(x)
Purpose: Shuffle the contents of an array in place.

In [25]:
np.random.shuffle(x)
print(x)


[0 4 2 9 6 5 8 3 7 1]
